# Generated by Django 2.2.24 on 2021-06-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Originalname', models.CharField(max_length=100)),
                ('NameInSpain', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=8)),
                ('Director', models.CharField(max_length=50)),
                ('Duration', models.PositiveSmallIntegerField()),
                ('Genres', models.CharField(max_length=200)),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '5'), (5, '5')], default=0)),
            ],
        ),
    ]
